faculty/faculty-interface-symfony-4/src/Entity/Students.php
<?php

namespace App\Entity;
use Symfony\Component\Security\Core\User\UserInterface;
use Doctrine\ORM\Mapping as ORM;

/**
 * Students
 *
 * @ORM\Table(name="students")
 * @ORM\Entity
 */
class Students implements UserInterface
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="idnum", type="string", length=10, nullable=false)
     */
    private $idnum;

    /**
     * @var string
     *
     * @ORM\Column(name="fname", type="string", length=50, nullable=false)
     */
    private $fname;

    /**
     * @var string
     *
     * @ORM\Column(name="mname", type="string", length=50, nullable=false)
     */
    private $mname;

    /**
     * @var string
     *
     * @ORM\Column(name="lname", type="string", length=50, nullable=false)
     */
    private $lname;

    /**
     * @var string
     *
     * @ORM\Column(name="entlev", type="string", length=20, nullable=false)
     */
    private $entlev;

    /**
     * @var string
     *
     * @ORM\Column(name="academic_year", type="string", length=50, nullable=false)
     */
    private $academicYear;

    /**
     * @var string
     *
     * @ORM\Column(name="term", type="string", length=20, nullable=false)
     */
    private $term;

    /**
     * @var string
     *
     * @ORM\Column(name="program", type="string", length=50, nullable=false)
     */
    private $program;

    /**
     * @var string
     *
     * @ORM\Column(name="class", type="string", length=20, nullable=false)
     */
    private $class;

    /**
     * @var string
     *
     * @ORM\Column(name="gender", type="string", length=10, nullable=false)
     */
    private $gender;

    /**
     * @var string
     *
     * @ORM\Column(name="cnum", type="string", length=20, nullable=false)
     */
    private $cnum;

    /**
     * @var string
     *
     * @ORM\Column(name="email", type="string", length=50, nullable=false)
     */
    private $email;

    /**
     * @var string
     *
     * @ORM\Column(name="prevschool", type="string", length=80, nullable=false)
     */
    private $prevschool;

    /**
     * @var string
     *
     * @ORM\Column(name="hea", type="string", length=50, nullable=false)
     */
    private $hea;

    /**
     * @var string
     *
     * @ORM\Column(name="img", type="string", length=50, nullable=false)
     */
    private $img;

    /**
     * @var string
     *
     * @ORM\Column(name="g_moral", type="string", length=50, nullable=false)
     */
    private $gMoral;

    /**
     * @var string
     *
     * @ORM\Column(name="NSO", type="string", length=50, nullable=false)
     */
    private $nso;

    /**
     * @var string
     *
     * @ORM\Column(name="reg_date", type="string", length=30, nullable=false)
     */
    private $regDate;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $password;

    /**
     * @ORM\Column(type="json", nullable=true)
     */
    private $proofpayment = [];

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $reviewcenter;

    /**
     * @ORM\Column(type="json", nullable=true)
     */
    private $extrafees = [];

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdnum(): ?string
    {
        return $this->idnum;
    }

    public function setIdnum(string $idnum): self
    {
        $this->idnum = $idnum;

        return $this;
    }

    public function getFname(): ?string
    {
        return $this->fname;
    }

    public function setFname(string $fname): self
    {
        $this->fname = $fname;

        return $this;
    }

    public function getMname(): ?string
    {
        return $this->mname;
    }

    public function setMname(string $mname): self
    {
        $this->mname = $mname;

        return $this;
    }

    public function getLname(): ?string
    {
        return $this->lname;
    }

    public function setLname(string $lname): self
    {
        $this->lname = $lname;

        return $this;
    }

    public function getEntlev(): ?string
    {
        return $this->entlev;
    }

    public function setEntlev(string $entlev): self
    {
        $this->entlev = $entlev;

        return $this;
    }

    public function getAcademicYear(): ?string
    {
        return $this->academicYear;
    }

    public function setAcademicYear(string $academicYear): self
    {
        $this->academicYear = $academicYear;

        return $this;
    }

    public function getTerm(): ?string
    {
        return $this->term;
    }

    public function setTerm(string $term): self
    {
        $this->term = $term;

        return $this;
    }

    public function getProgram(): ?string
    {
        return $this->program;
    }

    public function setProgram(string $program): self
    {
        $this->program = $program;

        return $this;
    }

    public function getClass(): ?string
    {
        return $this->class;
    }

    public function setClass(string $class): self
    {
        $this->class = $class;

        return $this;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(string $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function getCnum(): ?string
    {
        return $this->cnum;
    }

    public function setCnum(string $cnum): self
    {
        $this->cnum = $cnum;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPrevschool(): ?string
    {
        return $this->prevschool;
    }

    public function setPrevschool(string $prevschool): self
    {
        $this->prevschool = $prevschool;

        return $this;
    }

    public function getHea(): ?string
    {
        return $this->hea;
    }

    public function setHea(string $hea): self
    {
        $this->hea = $hea;

        return $this;
    }

    public function getImg(): ?string
    {
        return $this->img;
    }

    public function setImg(string $img): self
    {
        $this->img = $img;

        return $this;
    }
    public function getFullname(): ?string
    {
        return $this->fname ." ". $this->mname ." ". $this->lname;
    }

    public function getGMoral(): ?string
    {
        return $this->gMoral;
    }

    public function setGMoral(string $gMoral): self
    {
        $this->gMoral = $gMoral;

        return $this;
    }

    public function getNso(): ?string
    {
        return $this->nso;
    }

    public function setNso(string $nso): self
    {
        $this->nso = $nso;

        return $this;
    }

    public function getRegDate(): ?string
    {
        return $this->regDate;
    }

    public function setRegDate(string $regDate): self
    {
        $this->regDate = $regDate;

        return $this;
    }

    public function getRoles(){
        
        // guarantee every user at least has ROLE_USER
       

        return array('ROLE_USER','STUDENT');
    }
    public function getPassword(){
         

        return $this->password;
    }
    public function getSalt(){

    }
    public function eraseCredentials(){

    }
    public function getUsername(){
        return $this->email;   
    }

    public function setPassword(?string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getProofpayment(): ?array
    {
        return $this->proofpayment;
    }

    public function setProofpayment(?array $proofpayment): self
    {
        $this->proofpayment = $proofpayment;

        return $this;
    }

    public function getReviewcenter(): ?string
    {
        return $this->reviewcenter;
    }

    public function setReviewcenter(?string $reviewcenter): self
    {
        $this->reviewcenter = $reviewcenter;

        return $this;
    }

    public function getExtrafees(): ?array
    {
        return $this->extrafees;
    }

    public function setExtrafees(?array $extrafees): self
    {
        $this->extrafees = $extrafees;

        return $this;
    }
}

faculty/faculty-interface-symfony-4/templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {# Run `composer require symfony/webpack-encore-bundle`
           and uncomment the following Encore helpers to start using Symfony UX #}
        {% block stylesheets %}
            
        {% endblock %}
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico"/>
	<!-- CUSTOM STYLESHEET -->
	
	<!-- FONT AWESOME -->
	<script src="https://kit.fontawesome.com/575abfd474.js" crossorigin="anonymous"></script>
	<!-- BOOTSTRAP -->
    

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        {% block javascripts %}
            {#{{ encore_entry_script_tags('app') }}#}
        {% endblock %}
    {% if app.user is not empty and app.user.roles[0] == "FACULTY"%}
          <style>
          .wrapper .sidebar{
    z-index: 1;
    background: #FFF;
    box-shadow: 10px 10px 15px grey;
    position: fixed;
    top: 70px;
    width: 180px;
    height: calc(100% - 9%);
    transition: 0.3s;
    transition-property: width;
    overflow-y: auto;
  }
  .wrapper .sidebar .sidebar-menu{
    overflow: hidden;
  }
  .wrapper .sidebar .sidebar-menu .profile img{
    margin: 20px 0;
    width: 90px;
    height: 90px;
  }
  .wrapper .sidebar .sidebar-menu .profile p{
    color: grey;
    font-weight: 650;
  }
  .wrapper .sidebar .sidebar-menu .item{
    width: 250px;
    overflow: hidden;
    font-size: 14px;
  }
  .wrapper .sidebar .sidebar-menu .item a{
    text-decoration: none;
  }
  .wrapper .sidebar .sidebar-menu .item .menu-btn{
    display: block;
    color: #000;
    position: relative;
    padding: 10px 20px;
    transition: 0.3s;
    transition-property: color;
  }
  .wrapper .sidebar .sidebar-menu .item button {
      border: none;
      background: none;
  }
  .wrapper .sidebar .sidebar-menu .item button:hover {
      color: #FFF;
  }
  /********** SIDEBAR BUTTONS **********/
  .wrapper .sidebar .sidebar-menu .item .menu-btn span{
      padding: 20px;
      background: #A41034;
      border-radius: 2em;
      color: #fff;
  }
  .wrapper .sidebar .sidebar-menu .item .menu-btn span:hover{
      background: #C2133D;
  }
  .wrapper .sidebar .sidebar-menu .item .menu-btn:hover{
      background: #C2133D;
      color: #FFF;
      text-decoration: none;
  }
  .wrapper .sidebar .sidebar-menu .item .menu-btn i{
      margin-right: 20px;
  }
  /********** LOGOUT MODAL **********/
  .modal .modal-dialog .modal-content .modal-footer button {
      font-size: 14px;
  }
  .modal .modal-dialog .modal-content .modal-footer button a {
      text-decoration: none;
      color: #FFF;
  }
  
  
  
  /********** MAIN CONTAINER **********/
  .wrapper .content{
    width: (100% - 250px);
    margin-top: 70px;
    margin-left: 220px;
    padding: 15px;
    background-size: cover;
    height: 100vh;
    transition: 0.3s;
  }
        </style>
    {% else %}
    <link rel="stylesheet" href="{{ app.request.schemeAndHttpHost}}/assets/dashboard.css">
    <link rel="stylesheet" href="{{ app.request.schemeAndHttpHost }}/assets/css/style.css"/>
    <link rel="stylesheet" href="{{ app.request.schemeAndHttpHost }}assets/css/style-media-queries.css"/>
    
    <link rel="stylesheet" href="//cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="//cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css">
    <link href="https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css" rel="stylesheet" />

  
    {% endif %}

    </head>
    <body>
    <div class="wrapper">

        {% if app.user is not empty %}
        <div class="sidebar">
            <div class="sidebar-menu">
            <center class="profile">
                    <img src={{asset('assets/logo.png')}} alt="">
                    
                    <p>{{ app.user.fullname }}</p>
                </center>
                <hr></hr>
                
                {% if app.user.roles[1] == "FACULTY" %}
                
                <li class="item">
                    <a href="/dashboard" class="menu-btn">
                    
                    {% if app.request.uri == "http://127.0.0.1:8000/dashboard" %}
                        
                        <span><i class="fas fa-desktop"></i>Dashboard</span>
                        
                    {% else %}
                        <i class="fas fa-desktop"></i>Dashboard
                    {% endif %}
                    </a>
                </li>
                <li class="item">
                    <a href="/student" class="menu-btn">
                    {% if  app.request.uri == "http://127.0.0.1:8000/student" %}
                        
                            <span><i class="fas fa-graduation-cap"></i>Student</span>
                            
                        {% else %}
                            <i class="fas fa-graduation-cap"></i>Student
                        {% endif %}
                        
                    </a>
                </li>
                <li class="item">
                    <a href="/grading" class="menu-btn">
                    {% if app.request.uri == "http://127.0.0.1:8000/grading" %}
                        
                            <span><i class="fas fa-file-excel"></i>Grading</span>
                            
                        {% else %}
                            <i class="fas fa-file-excel"></i>Grading
                        {% endif %}
                        
                    </a>
                </li>
                <li class="item">
                    <a href="/profile" class="menu-btn">
                        <i class="fas fa-users-cog"></i>Profile
                    </a>
                </li>
                <li class="item">
                    <a href="/subjects" class="menu-btn">
                        <i class="fas fa-users-cog"></i>Subjects
                    </a>
                </li>
                <li class="item">
                    <a  href="{{ path('app_logout') }}" class="menu-btn">
                        <i class="fas fa-sign-out-alt"></i>Logout
                    </a>
                </li>
                {% else %}
                
            <ul class="sidebar-menu">
                <li class={{app.request.uri == "http://127.0.0.1:8000/dashboard"?"active":""}}>
                    <a href="/dashboard"><i class="bx bxs-dashboard"></i> Dashboard</a>
                </li>
                
                <li class={{app.request.uri == "http://127.0.0.1:8000/classrooms"?"active":""}}>
                    <a href="/classrooms"><i class='bx bxs-grid'></i>Classroom</a>
                </li>
                <li class="sidebar-subholder" style="display:none;" >
                    <i class='bx bxs-face'></i> Classroom
                    <ul class="sidebar-submenu">
                        <li>
                            <a href="room.html"><i class='bx bxs-face'></i>Room</a>
                        </li>
                        <li>
                            <a href="class.html"><i class='bx bxs-face'></i>Class</a>
                        </li>
                    </ul>
                </li>
                <li
                class={{app.request.uri == "http://127.0.0.1:8000/grades"?"active":""}}
                ><a href="/grades"> <i class='bx bxs-book-content'></i>Grades</a></li>
                <li
                class={{app.request.uri == "http://127.0.0.1:8000/profile/uploadpayment"?"active":""}}
                ><a href="{{path("showUploadPayment")}}"> <i class='bx bxs-credit-card-alt'></i>Payment</a>
                </li>

                <li><a href="{{ path('app_logout') }}">
                            
                                <i class='bx bxs-door-open'></i>Logout
                            
                        </a></li>
            </ul>
                {% endif %}
                <!-- Button trigger modal -->   
                
                
                
                
            </div>
        </div>
        

        {% endif %}
                {% block body %}{% endblock %}
        </div>


        
    </body>
</html>