faculty/faculty-interface-symfony-4/src/Entity/Activities.php
<?php

namespace App\Entity;

use App\Repository\ActivitiesRepository;
use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\Form\FormBuilderInterface;
/**
 * @ORM\Entity(repositoryClass=ActivitiesRepository::class)
 */
class Activities 
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $activityname;

    /**
     * @ORM\Column(type="json")
     */
    private $questions = [];

    /**
     * @ORM\Column(type="datetime")
     */
    private $timestamp;

    /**
     * @ORM\Column(type="integer")
     */
    private $facultyload_id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $activity_deadline;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $file;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $activitytype;

    /**
     * @ORM\Column(type="integer")
     */
    private $maxscore;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Course;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ProgramClass;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $tasktype;


    /**
     * @ORM\Column(type="boolean")
     */
    private $allowfileupload;

    /**
     * @ORM\Column(type="integer")
     */
    private $maxattempt;

    /**
     * @ORM\Column(type="json",nullable=true)
     */
    private $timer;

    

    

    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getActivityname(): ?string
    {
        return $this->activityname;
    }

    public function setActivityname(string $activityname): self
    {
        $this->activityname = $activityname;

        return $this;
    }

    public function getQuestions(): ?array
    {
        return $this->questions;
    }

    public function setQuestions(array $questions): self
    {
        $this->questions = $questions;

        return $this;
    }

    public function getTimestamp(): ?\DateTimeInterface
    {
        return $this->timestamp;
    }

    public function setTimestamp(\DateTimeInterface $timestamp): self
    {
        $this->timestamp = $timestamp;

        return $this;
    }

    public function getFacultyloadId(): ?int
    {
        return $this->facultyload_id;
    }

    public function setFacultyloadId(int $facultyload_id): self
    {
        $this->facultyload_id = $facultyload_id;

        return $this;
    }

    public function getActivityDeadline(): ?\DateTimeInterface
    {
        return $this->activity_deadline;
    }

    public function setActivityDeadline(\DateTimeInterface $activity_deadline): self
    {
        $this->activity_deadline = $activity_deadline;

        return $this;
    }

    public function getFile()
    {
        return $this->file;
    }

    public function setFile($file): self
    {
        $this->file = $file;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getActivitytype(): ?string
    {
        return $this->activitytype;
    }

    public function setActivitytype(string $activitytype): self
    {
        $this->activitytype = $activitytype;

        return $this;
    }

    public function getMaxscore(): ?int
    {
        return $this->maxscore;
    }

    public function setMaxscore(int $maxscore): self
    {
        $this->maxscore = $maxscore;

        return $this;
    }

    public function getCourse(): ?string
    {
        return $this->Course;
    }

    public function setCourse(string $Course): self
    {
        $this->Course = $Course;

        return $this;
    }

    public function getProgramClass(): ?string
    {
        return $this->ProgramClass;
    }

    public function setProgramClass(string $ProgramClass): self
    {
        $this->ProgramClass = $ProgramClass;

        return $this;
    }

    public function getTasktype(): ?string
    {
        return $this->tasktype;
    }

    public function setTasktype(string $tasktype): self
    {
        $this->tasktype = $tasktype;

        return $this;
    }

 

    public function getAllowfileupload(): ?bool
    {
        return $this->allowfileupload;
    }

    public function setAllowfileupload(bool $allowfileupload): self
    {
        $this->allowfileupload = $allowfileupload;

        return $this;
    }

    public function getMaxattempt(): ?int
    {
        return $this->maxattempt;
    }

    public function setMaxattempt(int $maxattempt): self
    {
        $this->maxattempt = $maxattempt;

        return $this;
    }

    public function getTimer(): ?array
    {
        return $this->timer;
    }

    public function setTimer(?array $timer): self
    {
        $this->timer = $timer;

        return $this;
    }

  

   
    
   
}

faculty/faculty-interface-symfony-4/src/Entity/Students.php
<?php

namespace App\Entity;
use Symfony\Component\Security\Core\User\UserInterface;
use Doctrine\ORM\Mapping as ORM;

/**
 * Students
 *
 * @ORM\Table(name="students")
 * @ORM\Entity
 */
class Students implements UserInterface
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="idnum", type="string", length=10, nullable=false)
     */
    private $idnum;

    /**
     * @var string
     *
     * @ORM\Column(name="fname", type="string", length=50, nullable=false)
     */
    private $fname;

    /**
     * @var string
     *
     * @ORM\Column(name="mname", type="string", length=50, nullable=false)
     */
    private $mname;

    /**
     * @var string
     *
     * @ORM\Column(name="lname", type="string", length=50, nullable=false)
     */
    private $lname;

    /**
     * @var string
     *
     * @ORM\Column(name="entlev", type="string", length=20, nullable=false)
     */
    private $entlev;

    /**
     * @var string
     *
     * @ORM\Column(name="academic_year", type="string", length=50, nullable=false)
     */
    private $academicYear;

    /**
     * @var string
     *
     * @ORM\Column(name="term", type="string", length=20, nullable=false)
     */
    private $term;

    /**
     * @var string
     *
     * @ORM\Column(name="program", type="string", length=50, nullable=false)
     */
    private $program;

    /**
     * @var string
     *
     * @ORM\Column(name="class", type="string", length=20, nullable=false)
     */
    private $class;

    /**
     * @var string
     *
     * @ORM\Column(name="gender", type="string", length=10, nullable=false)
     */
    private $gender;

    /**
     * @var string
     *
     * @ORM\Column(name="cnum", type="string", length=20, nullable=false)
     */
    private $cnum;

    /**
     * @var string
     *
     * @ORM\Column(name="email", type="string", length=50, nullable=false)
     */
    private $email;

    /**
     * @var string
     *
     * @ORM\Column(name="prevschool", type="string", length=80, nullable=false)
     */
    private $prevschool;

    /**
     * @var string
     *
     * @ORM\Column(name="hea", type="string", length=50, nullable=false)
     */
    private $hea;

    /**
     * @var string
     *
     * @ORM\Column(name="img", type="string", length=50, nullable=false)
     */
    private $img;

    /**
     * @var string
     *
     * @ORM\Column(name="g_moral", type="string", length=50, nullable=false)
     */
    private $gMoral;

    /**
     * @var string
     *
     * @ORM\Column(name="NSO", type="string", length=50, nullable=false)
     */
    private $nso;

    /**
     * @var string
     *
     * @ORM\Column(name="reg_date", type="string", length=30, nullable=false)
     */
    private $regDate;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $password;

    /**
     * @ORM\Column(type="json", nullable=true)
     */
    private $proofpayment = [];

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $reviewcenter;

    /**
     * @ORM\Column(type="json", nullable=true)
     */
    private $extrafees = [];

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdnum(): ?string
    {
        return $this->idnum;
    }

    public function setIdnum(string $idnum): self
    {
        $this->idnum = $idnum;

        return $this;
    }

    public function getFname(): ?string
    {
        return $this->fname;
    }

    public function setFname(string $fname): self
    {
        $this->fname = $fname;

        return $this;
    }

    public function getMname(): ?string
    {
        return $this->mname;
    }

    public function setMname(string $mname): self
    {
        $this->mname = $mname;

        return $this;
    }

    public function getLname(): ?string
    {
        return $this->lname;
    }

    public function setLname(string $lname): self
    {
        $this->lname = $lname;

        return $this;
    }

    public function getEntlev(): ?string
    {
        return $this->entlev;
    }

    public function setEntlev(string $entlev): self
    {
        $this->entlev = $entlev;

        return $this;
    }

    public function getAcademicYear(): ?string
    {
        return $this->academicYear;
    }

    public function setAcademicYear(string $academicYear): self
    {
        $this->academicYear = $academicYear;

        return $this;
    }

    public function getTerm(): ?string
    {
        return $this->term;
    }

    public function setTerm(string $term): self
    {
        $this->term = $term;

        return $this;
    }

    public function getProgram(): ?string
    {
        return $this->program;
    }

    public function setProgram(string $program): self
    {
        $this->program = $program;

        return $this;
    }

    public function getClass(): ?string
    {
        return $this->class;
    }

    public function setClass(string $class): self
    {
        $this->class = $class;

        return $this;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(string $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function getCnum(): ?string
    {
        return $this->cnum;
    }

    public function setCnum(string $cnum): self
    {
        $this->cnum = $cnum;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPrevschool(): ?string
    {
        return $this->prevschool;
    }

    public function setPrevschool(string $prevschool): self
    {
        $this->prevschool = $prevschool;

        return $this;
    }

    public function getHea(): ?string
    {
        return $this->hea;
    }

    public function setHea(string $hea): self
    {
        $this->hea = $hea;

        return $this;
    }

    public function getImg(): ?string
    {
        return $this->img;
    }

    public function setImg(string $img): self
    {
        $this->img = $img;

        return $this;
    }
    public function getFullname(): ?string
    {
        return $this->fname ." ". $this->mname ." ". $this->lname;
    }

    public function getGMoral(): ?string
    {
        return $this->gMoral;
    }

    public function setGMoral(string $gMoral): self
    {
        $this->gMoral = $gMoral;

        return $this;
    }

    public function getNso(): ?string
    {
        return $this->nso;
    }

    public function setNso(string $nso): self
    {
        $this->nso = $nso;

        return $this;
    }

    public function getRegDate(): ?string
    {
        return $this->regDate;
    }

    public function setRegDate(string $regDate): self
    {
        $this->regDate = $regDate;

        return $this;
    }

    public function getRoles(){
        
        // guarantee every user at least has ROLE_USER
       

        return array('ROLE_USER','STUDENT');
    }
    public function getPassword(){
         

        return $this->password;
    }
    public function getSalt(){

    }
    public function eraseCredentials(){

    }
    public function getUsername(){
        return $this->email;   
    }

    public function setPassword(?string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getProofpayment(): ?array
    {
        return $this->proofpayment;
    }

    public function setProofpayment(?array $proofpayment): self
    {
        $this->proofpayment = $proofpayment;

        return $this;
    }

    public function getReviewcenter(): ?string
    {
        return $this->reviewcenter;
    }

    public function setReviewcenter(?string $reviewcenter): self
    {
        $this->reviewcenter = $reviewcenter;

        return $this;
    }

    public function getExtrafees(): ?array
    {
        return $this->extrafees;
    }

    public function setExtrafees(?array $extrafees): self
    {
        $this->extrafees = $extrafees;

        return $this;
    }
}

faculty/faculty-interface-symfony-4/templates/grading/grade.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
<style>
    .search{
            padding: 6px 14px;
    border-radius: 6px;
    border: 1px solid grey;
    outline: none;
    }
        .view a {
            color: royalblue;
            text-decoration: none;
        }
        table {
            font-size: 15px;
        }

        .grade-table thead{
background-color:#023047;
color:white;
        }
        .table-add-grade tr{
vertical-align:middle;
        }
    </style>
{% endblock %}
{% block body %}
<div
class="wrapper"
>
 <div class="header">
            <div class="header-menu">
                <div class="title">Educa Academy</div>
            </div>
        </div>
        <div class="content">
         
            <div class="directory">
                <p>Grading / Grade my Student</p>
            </div>
            <hr></hr>

            <h5>Student Grading</h5>
                <button type="button" class="btn btn-danger" style="width: 100px;">
                Back</button>
            <input class="search" name="search" type="search" placeholder="Type search..." aria-label="Search">
            <br><br>
            <div class="flex">
                <div class="grades">
                    {%if stud.reviewcenter != "LET"%}
                    <table class="table table-bordered grade-table">
                        <thead >
                            <tr>
                                <th>Grade Range</th>
                                <th>Grade Point</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>96-100</td>
                                <td>4.0</td>
                            </tr>
                            <tr>
                                <td>90-95</td>
                                <td>3.5</td>
                            </tr>
                            <tr>
                                <td>84-89</td>
                                <td>3.0</td>
                            </tr>
                            <tr>
                                <td>78-83</td>
                                <td>2.5</td>
                            </tr>
                            <tr>
                                <td>72-77</td>
                                <td>2.0</td>
                            </tr>
                            <tr>
                                <td>66-71</td>
                                <td>1.5</td>
                            </tr>
                            <tr>
                                <td>60-65</td>
                                <td>1.0</td>
                            </tr>
                            <tr>
                                <td>59 and below</td>
                                <td>R</td>
                            </tr>
                        </tbody>
                    </table>
                    {%else%}
                    
                    {%endif%}
                </div>

                <div class="add-grades">
                    {{ form_start(form) }}
                    <table class="table table-hover table-add-grade">
                        <tr>
                            <th>Course Name </th>

                            <th>Name    </th>
                            {% if stud.reviewcenter != "LET" %}
                            <th>Interim 1</th>
                            <th>Midterm</th>
                            <th>Interim 2</th>
                            <th>Final</th>
                            <th>Grade</th>
                            <th>Remark</th>
                            {% else %}
                            <th>Remark</th>
                            {% endif %}
                        </tr>
                            {% for s in students %}
                            <tbody>
                                <tr>
                                    <td>{{ s.course }}</td>
                                    <td>{{ s.fullname }}</td>
                                    {% if stud.reviewcenter != "LET" %}
                                    <td>{{ form_row(form.interim1)}}</td>
                                    <td>{{ form_row(form.midterm) }}</td>
                                    <td>{{ form_row(form.interim2) }}</td>
                                    <td>{{ form_row(form.final) }}</td>
                                    <td>{{ s.Grade }}</td>
                                    <td>{{ s.Remarks }}</td>
                                    {% else %}
                                    <td>{{ form_row(form.remarks) }}</td>
                                    {% endif%}
                                    
                                </tr>
                            </tbody>
                            {% endfor %}
                    </table>
                    <div class="save">
                        {{ form_row(form.save) }}
                    </div>
                    {{ form_end(form) }}
                </div>
            </div> 
        </div>
    

</div>
         {% endblock %}

faculty/faculty-interface-symfony-4/templates/grading/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} Grade my Student {% endblock %}

{% block stylesheets %}
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico"/>
	<!-- CUSTOM STYLESHEET -->
	<link rel="stylesheet" href="assets/grading.css">
	<!-- FONT AWESOME -->
	<script src="https://kit.fontawesome.com/575abfd474.js" crossorigin="anonymous"></script>
	<!-- BOOTSTRAP -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <style>
        body {
            background: #EEEEEE;
        }
        .search {
            float: right;
            width: 200px;
            height: 40px;
            border-radius: 2em;
            padding: 10px;
            border: none;
            box-shadow: 10px 10px 15px grey;
            font-size: 14px;
        }
    </style>
{% endblock %}

{% block body %}
<body>
    <!--wrapper start-->
    <div class="wrapper">
        <!--header menu start-->
        <div class="header">
            <div class="header-menu">
                <div class="title">Educa Academy</div>
            </div>
        </div>
        <!--header menu end-->
        <!--sidebar start-->
          
        <!--sidebar end-->
        <!--main container start-->
        <div class="content">
            <div class="directory">
                <p>Grading / </p>
            </div>
            <hr></hr>

            <h5>Student Grading</h5>
            <button type="button" class="btn btn-def" id="gradestud" >Create Grade Component</button>
            <input class="search" name="search" type="search" placeholder="Type search..." aria-label="Search">
            <br><br>
            <div class="grades">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Grade Range</th>
                            <th>Grade Point</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>96-100</td>
                            <td>4.0</td>
                        </tr>
                        <tr>
                            <td>90-95</td>
                            <td>3.5</td>
                        </tr>
                        <tr>
                            <td>84-89</td>
                            <td>3.0</td>
                        </tr>
                        <tr>
                            <td>78-83</td>
                            <td>2.5</td>
                        </tr>
                        <tr>
                            <td>72-77</td>
                            <td>2.0</td>
                        </tr>
                        <tr>
                            <td>66-71</td>
                            <td>1.5</td>
                        </tr>
                        <tr>
                            <td>60-65</td>
                            <td>1.0</td>
                        </tr>
                        <tr>
                            <td>59 and below</td>
                            <td>R</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            
        </div>
        <!--main container end-->
    </div>
    <script>
    document.getElementById("gradestud").addEventListener('click',()=>{
        window.location.replace("/grade");
    });
    </script>
    <!--wrapper end-->

    </div>
</body>
{% endblock %}